<?php

namespace App\Console\Commands;

use App\User;
use Illuminate\Console\Command;
use Symfony\Component\Console\Input\InputArgument;

class ElickCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'elick:command {name=elick} {--mark=!}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function fire()
    {
        //建立迁移文件
//        $name = 'add_cashier_columns';
//        $path = database_path().'/migrations';
//        $this->laravel['migration.creator']->create($name,$path);
//        dump($this->laravel);
        //error并不能自动退出 是我的bye是退出的意思
        $this->error('quit');

        $name = $this->argument('name');
        $mark = $this->option('mark');
        $info = 'Hello '.$name.$mark."\n";
        //用echo的话在浏览器也能显示 用info就不可以了
        echo $info;
        //$this->info($info);

        $say = $this->ask('Would you like something to drink ');
        $this->info("ok! ".$say."\n");

        if($this->confirm('Do you want to continue?[y|n]')) {

            $pwd = $this->secret('Please write your password');
            $this->info('your password is ' . $pwd . "\n");
        }else{
            $this->comment("Interrupt");
        }

        $name = $this->choice('Would you like something to drink ?',['coffee','tea','cococola']);
        $this->question($name);


        $headers = ['Name','Email'];
        $users = User::all(['name','email']);
        $this->table($headers,$users);
//        $this->output->progressStart(10);
//        for ($i = 0; $i < 10; $i++) {
//            sleep(1);
//            $this->output->progressAdvance();
//        }
//
//        $this->output->progressFinish();

        $this->call('inspire');
        //阻止命令输出
        $this->callSilent('inspire');
        //$this->call('make:view');

        $this->error('Bye-bye');
    }


    //必须使用$name属性时 这个方法才可用
    /*
    protected function getArguments()
    {
        //return parent::getArguments(); // TODO: Change the autogenerated stub
        return [
            ['table',InputArgument::REQUIRED,'must be']
        ];
    }
    */
}
