<?php
/**
 * Created by PhpStorm.
 * User: elick
 * Date: 2016/3/29
 * Time: 22:00
 */
namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class TestClass extends Facade{
    protected static function  getFacadeAccessor()
    {
        //parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        //这里返回的就是$this->app->singleton('test',function(){}绑定的那个名
        return 'test';
    }
}